### ISSUE TITLE
Home page/Pregled predmeta/Povzetek is not modified

### ISSUE THREAD

**Issue by zigatrcek** [janvasiljevic/fri-dark-theme#1]
Replication procedure:

- log in
- on home page, go to Pregled predmeta, click the dropdown menu on the picture and press Povzetek

![image](https://user-images.githubusercontent.com/57506989/75378232-9e930380-58d3-11ea-8f98-61aa45a73b72.png)

![image](https://user-images.githubusercontent.com/57506989/75378255-a6eb3e80-58d3-11ea-8ad7-b97c972d32b1.png)

**Comment by janvasiljevic** [comment]
The issue has now been resolved

![image](https://user-images.githubusercontent.com/47833674/75388221-e3736600-58e4-11ea-8483-582897112e82.png)
