### ISSUE TITLE
Bad contrast ration on results.

### ISSUE THREAD

**Issue by LanVukusic** [janvasiljevic/fri-dark-theme#3]
If you submit your homework and try to view the number of points achieved on every exercise, the popup (the icon that shows after a hover), has white text on bright background thus making it hard to read.  
- Appended is the image of a preview of what it looks like

![image](https://user-images.githubusercontent.com/13378639/75715616-fc598e00-5ccd-11ea-8e72-cdf03751e72b.png)

**Comment by janvasiljevic** [comment]
The styling has now been fixed.
![image](https://user-images.githubusercontent.com/47833674/75726945-ff5f7900-5ce3-11ea-9b92-18e295a98cbe.png)
